/// <reference types="@raycast/api">

/* eslint-disable @typescript-eslint/no-empty-interface */

// This file is auto-generated by Raycast's build system.
// We declare it here for standalone TypeScript checking.

interface Preferences {
  vaultPath: string;
  excludedFolders: string;
  includedFolders: string;
  inboxFilePath: string;
  showCompletedTasks: boolean;
  sortByPriority: boolean;
  showOnlyCurrent: boolean;
  showDueDate: boolean;
  menubarTaskCount: boolean;
  showIcon: boolean;
  maxMenubarDescriptionLength: string;
  refreshIntervalInMinutes: string;
}

interface Preferences_ListTasks extends Preferences {}
interface Preferences_AddTask extends Preferences {}
interface Preferences_EditTask extends Preferences {}
interface Preferences_MarkDone extends Preferences {}
interface Preferences_MenubarItem extends Preferences {}
